var BrewingDataSet = [
      ["1", "Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer", "Grog", "<ol><li>1-3 bushals of horse food</li><li>cook for 8-10 mins</li><li>age for a couple days in a certain barrel</li></ol>", "2","n/a"],
      ["2", "Skunky Beer/Beer/Fine Beer", "Grog", "Double the ingredients of wheatbeer, cook for 6-10 mins, age for a few days in a certain barrel", "2","n/a"],
      ["3", "Skunky Darkbeer/Darkbeer/Fine Darkbeer", "Grog", "4-8 bushals of horse food, cook for 6-10 mins, age for a week and a bit in a dark-ish barrel", "2","n/a"],
      ["4", "Awkward Mead/Mead/Golden Mead", "Grog", "4-8 sweet tasting reeds, cook for 1-3 mins, age for a few days in a certain barrel", "2","n/a"],
      ["5", "Apple Mead/Sweet Apple Mead/Sweet Golden Apple Mead", "Grog", "A few of those reeds, plus a couple of fruits, cook for a few mins, age for a few days", "2","n/a"],
      ["6", "Bitter Rum/Spicy Rum/Golden Rum", "Grog", "A lot of reeds to make it extra sweet, cook for 5-8 mins, distill it a few times, and age it for a couple weeks", "2","n/a"],
      ["7", "Lousy Vodka/Vodka/Russian Vodka", "Grog", "A bunch of earth-apples, distilled a few times makes for the perfect Russian drink", "2","n/a"],
      ["8", "Poor Absinthe/Absinthe/Strong Absinthe", "Grog", "10-16 pieces of overgrown grass, cook for a few minutes, distill 4-6 times for a minute each", "2","n/a"],
      ["9", "Potato soup", "Grog", "A handful of the obvious plus some overgrown grass, cook for a few minutes", "2","n/a"],
      ["10", "Stale Coffee/Coffee/Strong Coffee", "Grog", "8-12 of midnight dye with a touch of milk, don't let it overcook!", "2","n/a"],
      ["11", "Cold Tea/Tea/Oolong Tea", "Grog", "2-8 pieces of watery reeds with some overgrown grass, let it cook for a few minutes for a succulent taste", "2","n/a"],
      ["12", "Tequila Blanco/Tequila Gold/Tequila Anejo", "Grog", "5-10 *ow*..pieces of *ouch*.., cook for 8-10 mins, with a few distill runs of 30-40 secs", "2","n/a"],
      ["13", "Melon Smoothie", "Grog", "10-16 of the obvious with a few pieces of frozen water to keep it cool, cook for a couple minutes for a refreshing drink", "2","n/a"],
      ["14", "Diluted Grog/Grog/Strong Grog", "Grog", "2-4 pieces of horse grub, 0-2 pieces of reeds, and 2-3 pieces of tree fruit and watery fruit, cook for 5-6 minutes, distill, and enjoy it with yar fellow mates", "2","n/a"],
      ["15", "Blueberry Smoothie", "Grog", "10-16 of the finest blue, a dash of milk just for you, 1-4 sugar to sweeten it up, and 2 parts of ice for endless luck, cook for a few minutes", "2","n/a"],
      ["16", "Ambassador", "Grog", "3-8 oranges, a piece of something that glows, and a dash of sugar, cook for 2-4 mins", "2","n/a"],
      ["17", "Bora Bora", "Grog", "Some overgrown grass and a dash of milk, to be cooked for 2-6 mins", "2","n/a"],
      ["18", "Flat Hard-Cider/Hard-Cider/Cap`n Barbosa", "Grog", "3-5 of Barbosa's fruit, 1-4 sweet reeds, and something fermented, cook for 3-5 mins, distill a few times, age in an orange barrel for a few days", "2","n/a"],
      ["19", "Stale Toadstool Tea/Toadstool Tea/Bag o` Filth", "Grog", "12-16 pieces of fungi, 1-3 pieces of cow food, 3-5 miniature trees, and a piece of creeper essence, cook for 1-3 mins", "2","n/a"],
      ["20", "Sour Tropical Punch/Tropical Punch/Caribbean Smuggler", "Grog", "6-8 pieces of spikey tree, 7-10 Barbossa's fruit, 1-2 fairy dust, and a handful of gold doubloons, cook for 10-15 mins, distill a few times, don't get caught!", "2","n/a"],
      ["21", "Stale Pumpkin-Spice Latte/Pumpkin-Spice Latte/Creamy Pumpkin-Spice Latte", "Grog", "5-10 halloween seeds, 0-2 carved fruit, 6-10 chocolatey beans, 3-5 spoonfuls of sweetener, and just a dash of milk, cook for 4-8 mins, distill a few times, enjoy with some cookies", "2","n/a"],
      ["22", "Cold Pirate Tea/Pirate Tea/Hot Pirate Tea", "Grog", "1-5 miniature trees, 1-4 villager coins, 5-7 pieces of refined reeds, cook for 4-6 mins, distill, and serve", "2","n/a"],
      ["23", "6FootUnder Apple-Pie Shine/Apple-Pie Shine/Cloud-9 Apple-Pie Shine", "Grog", "7-12 tree fruits, 0-2 jeweled fruit, 5-7 horse food, and 4-8 sweet reeds, cook for 10-15 mins, distill 2-6 times for 20 secs", "2","n/a"],
      ["24", "Stale Watermelon Brandy/Watemelon Brandy/Fog Cutter", "Grog", "1-5 pieces of jeweled water fruit, 1-5 pieces of jeweled fruit, cook for 6-8 mins, distill a couple times, age in a tropical barrel for 1-6 days", "2","n/a"],
      ["25", "Junky Bourbon/Bourbon/Pirate's Kiss", "Grog", "","0","n/a"],
      ["26", "Rancid EggNog/EggNog/Crow's Nest", "Grog", "","0","n/a"],
      ["27", "Cheap Champagne/Champagne/Jeweled Champagne", "Grog", "","0","n/a"],
      ["28", "Sun Tea/Sweet Tea/Iced Sweet Tea", "Grog", "","0","n/a"],
      ["29", "Golden Pale Ale/Golden Ale/Golden Pelican Ale", "Grog", "","0","n/a"],
      ["30", "Shady Shiraz/Shiraz/Syrah", "Grog", "","0","n/a"],
      ["31", "Stale Scotch/Scotch/Pissin' Parrot", "Grog", "","0","n/a"],
      ["32", "Almost-Bloody Mary/Bloody Mary/Bloody Hell", "Grog", "","0","n/a"],
      ["33", "Pucker Margarita/Margarita/Devil's Poison", "Grog", "","0","n/a"],
      ["34", "Battering Ram", "Grog", "","0","n/a"],
      ["35", "Weak Kamikaze/Kamikaze/Davey Jones' Locker", "Grog", "","0","n/a"],
      ["36", "Aged Rum/Kraken Rum/✪ God's Rum ✪", "Grog", "","0","n/a"],
      ["37", "Foul Pumpkin Ale/Fermented Pumpkin/Pumpkin Ale", "Grog", "","0","n/a"],
      ["38", "Rotten Cranberry Champagne/Cranberry Champagne/ Sparkling Cranberry Champagne", "Grog", "","0","n/a"],
      ["39", "Dull Hot Chocolate/Hot Chocolate/HotChocolate Marshmellows", "Grog", "","0","n/a"],
      ["40", "Flat Chai Tea/Chocolate Chai Tea/Soothing Chocolate Tea", "Grog", "","0","n/a"],
      ["41", "Mold Wine/Mulled Wine/Crisp Mulled Wine", "Grog", "","0","n/a"],
      ["42", "Rotten Mocha/Peppermint Mocha/Hot Peppermint Mocha", "Grog", "","0","n/a"],
      ["43", "Spoiled Irish Cream/Irish Cream/Silky Irish Cream", "Grog", "","0","n/a"],
      ["44", "Donner Tini/Christmas Tini/Rudolph Tini", "Grog", "","0","n/a"],
      ["45", "Bitter Ginger Beer/Ginger Beer/Bubbly Ginger Beer", "Grog", "","0","n/a"],
      ["46", "Sake", "Grog", "","0","n/a"],
      ["47", "Blueberry Vodka", "Grog", "","0","n/a"],
      ["48", "Melted Melon Ice/Slushy Melon Ice/ Melon Italian Ice", "Grog", "","0","n/a"],
      ["49", "Sad Bears/Happy Bears/Greatful Dead Brew", "Grog", "","0","n/a"],
      ["50", "Sand Slide/Rock Slide/ MudSlide", "Grog", "","0","n/a"],
      ["51", "Black Fire Potion", "Grog", "","0","n/a"],
      ["52", "Blood Replenishing Potion", "Grog", "","0","n/a"],
      ["53", "Polymilk Potion", "Grog", "","0","n/a"],
      ["54", "Epic Potion", "Grog", "","0","n/a"],
      ["55", "Frog Potion", "Grog", "","0","n/a"],
      ["56", "Raging Potion", "Grog", "","0","n/a"],
      ["57", "Trickster", "Grog", "","0","n/a"],
      ["58", "Truth Potion", "Grog", "","0","n/a"],
      ["59", "Mole Hole Potion", "Grog", "","0","n/a"],
      ["60", "Flat Lemon Pop/Lemon-Lime Soda/Lemon-Lime Soda", "Grog", "","0","n/a"],
      ["61", "Flat Cola/Dark Cola/Tangy Dark Cola ", "Grog", "","0","n/a"],
      ["62", "Ambrosia", "Grog", "","0","n/a"],
      ["63", "BLINDRAGE", "Grog", "","0","n/a"],
      ["64", "Cherry Blossom Rum", "Grog", "","0","n/a"],
      ["65", "Cinnamon Schnapps/Fireball/Liquid Fire", "Grog", "","0","n/a"],
      ["66", "Old Gold", "Grog", "","0","n/a"],
      ["67", "Strawberry Juice/Dry Martini/Strawberry Martini", "Grog", "","0","n/a"],
      ["68", "Sludge/Slimy Vodka/Toxic Vodka", "Grog", "","0","n/a"],
      ["69", "Blue Goo/Kiwi Liqueur/Hypnotic", "Grog", "","0","n/a"],
      ["70", "❊The Arnold❊", "Grog", "","0","n/a"],
      ["71", "Poseidons Punch", "Grog", "","0","n/a"],
      ["72", "Diablos Nightmare", "Grog", "","0","n/a"],
      ["73", "Ender Juice", "Grog", "","0","n/a"],
      ["74", "Chowda", "Grog", "","0","n/a"],
      ["75", "Fizzy Lifting Drink", "Grog", "","0","n/a"],
      ["76", "Exotic Ale", "Grog", "","0","n/a"],
      ["77", "High West Distiller's Campfire", "Grog", "","0","n/a"],
      ["78", "$5 Shake", "Grog", "","0","n/a"],
      ["79", "Tres Generaciones Anejo", "Grog", "","0","n/a"],
      ["80", "Woody Creek Vodka", "Grog", "","0","n/a"],
      ["81", "White Russian", "Grog", "","0","n/a"],
      ["82", "Flaming MOE", "Grog", "","0","n/a"],
      ["83", "BUTTERBEER", "Grog", "","0","n/a"],
      ["84", "✞Kellster's Head Smasher✞", "Grog", "","0","n/a"],
      ["85", "Stirred Martini/Shaken Martini/Dirty Yetini", "Grog", "","0","n/a"],
      ["86", "✯Beard SPLITTER✯", "Grog", "","0","n/a"],
      ["87", "Unholy Water/Bottled Water/✝Holy Water✝", "Grog", "","0","n/a"],
      ["88", "Happy Godsy/Bleh Godsy/Raging Godsy", "Grog", "","0","n/a"],
      ["89", "☢Nette Bomb☢", "Grog", "","0","n/a"],
      ["90", "Pooh Bear/Sleep Bear/Grizzly Bear", "Grog", "","0","n/a"],
      ["91", "Waning Moon/Crescent Moon/☾Vape's Blue Moon☽", "Grog", "","0","n/a"],
      ["92", "Tart Moscato/Tangy Moscato/❥Smokey's Sweet Moscato❥", "Grog", "","0","n/a"],
      ["93", "☠Austrian Madman☠", "Grog", "","0","n/a"],
      ["94", "Coagulated Blood Tea/Blood Tea/Dragons Blood Awakening", "Grog", "","0","n/a"],
      ["95", "❦Cysteen's Blue Shell Beer❦", "Grog", "","0","n/a"],
      ["96", "Pineapple Juice/Coconut Milk/Pina Colada", "Grog", "","0","n/a"],
      ["97", "⍥Narwhale Nectar", "Grog", "","0","n/a"],
      ["98", "✦Tears of the Gods", "Grog", "","0","n/a"],
      ["99", "♆Devils Fruit Punch", "Grog", "","0","n/a"],
      ["100", "☸Navigators Elixer☸", "Grog", "","0","n/a"],
      ["101", "Gin/Spicy Gin/Bombay Sapphire", "Grog", "","0","n/a"],
      ["102", "Whiskey/Fine Whiskey/Golden Whiskey", "Grog", "","0","n/a"],
      ["103", "Liquor/Sweet Liquor/Golden Liquor", "Grog", "","0","n/a"],
      ["104", "Rancid Gravy/Fine Gravy/Yorkshireman's Gravy", "Grog", "","0","n/a"],
      ["105", "Fin Stew/Fin Brew/Sharkbait Brew", "Grog", "","0","n/a"],
      ["106", "Peppy's Kiss/Shocker Boy/Dudette Duo", "Grog", "","0","n/a"],
      ["107", "Cracked Wood/Rotting Wood/Driftwood", "Grog", "","0","n/a"],
      ["108", "Spring/Cog/Clockwork Soldier", "Grog", "","0","n/a"],
      ["109", "Morning Tide/Evening Tide/Midnight Tide", "Grog", "","0","n/a"],
      ["110", "Westward Breeze/Southerly Wind/Eastern Gale", "Grog", "","0","n/a"],
      ["111", "Devil's Delight/Devil's Love/Devil's Kiss", "Grog", "","0","n/a"],
      ["112", "Spectacular Flask/Dirty Flask/Bottle o' Filth", "Grog", "","0","n/a"],
      ["113", "Three Shot/Two Shot/One Shot", "Grog", "","0","n/a"],
      ["114", "Lime Juice/Lime Love/Lime Lust", "Grog", "","0","n/a"],
      ["115", "Citrus Shake/Mango Cocktail/Tuvalu Tropicana", "Grog", "","0","n/a"],
      ["116", "Currents/Whirlpool/Maelstrom", "Grog", "","0","n/a"],
      ["117", "Square Rig/Flying Jibb/Windjammer", "Grog", "","0","n/a"],
      ["118", "Tiki Elixir/Totem Elixir/Voodoo Elixir", "Grog", "","0","n/a"],
      ["119", "Eradicator/Vindicator/Syndicator", "Grog", "","0","n/a"],
      ["120", "Mackerel Milkshake/Trout Tini/Goldfish", "Grog", "","0","n/a"],
      ["121", "Coconut Shake/Aloha Ale/Krakatoa", "Grog", "","0","n/a"],
      ["122", "Templar Grog/Crusaders Brew/Deus Vult", "Grog", "","0","n/a"],
      ["123", "Steam Pinata/Steal Balloon/Led Zepplin", "Grog", "","0","n/a"],
      ["124", "Dolphin Dash/Whaler's Poison/Moby Dick", "Grog", "","0","n/a"],
      ["125", "What Wolf/When Wolf/Werewolf", "Grog", "","0","n/a"],
      ["126", "Hot Cocoa/Cocoa Brew/Chocolate Liquor", "Grog", "","0","n/a"],
      ["127", "OwO/UwU/Fwendship Potion owo", "Grog", "","0","n/a"],
      ["128", "Lighthouse Lampoon", "Grog", "","0","n/a"],
      ["129", "Nepalese Dragon Dance", "Grog", "","0","n/a"],
      ["130", "Utopia", "Grog", "","0","n/a"],
      ["131", "Piano Man", "Grog", "","0","n/a"],
      ["132", "Pompeii Pinata", "Grog", "","0","n/a"],
      ["133", "Asylum's Ale", "Grog", "","0","n/a"],
      ["134", "Chatham Brandy", "Grog", "","0","n/a"],
      ["135", "Trenchcoat Tequila", "Grog", "","0","n/a"],
      ["136", "Tamer of the Hoards", "Grog", "","0","n/a"],
      ["137", "Hacksaw Crud", "Grog", "","0","n/a"],
      ["138", "Cracked Cocnut", "Grog", "","0","n/a"],
      ["139", "Fizzed Torch", "Grog", "","0","n/a"],
      ["140", "Golden Skull", "Grog", "","0","n/a"],
      ["141", "Fool's Gold", "Grog", "","0","n/a"],
      ["142", "Blood Lust", "Grog", "","0","n/a"],
      ["143", "Maiden's Poison", "Grog", "","0","n/a"],
      ["144", "Bahama Burst", "Grog", "","0","n/a"],
      ["145", "Sparrow's Quest", "Grog", "","0","n/a"],
      ["146", "Calypso's Curse", "Grog", "","0","n/a"],
      ["147", "Hazelnut Horchata", "Grog", "","0","n/a"],
      ["148", "Twilight Mist", "Grog", "","0","n/a"],
      ["149", "Sprung Leak", "Grog", "","0","n/a"],
      ["150", "Fermented Bilge Rat", "Grog", "","0","n/a"],
      ["151", "Calcutta Corpse", "Grog", "","0","n/a"],
      ["152", "Singapore Spice", "Grog", "","0","n/a"],
      ["153", "Emerald Glaze", "Grog", "","0","n/a"],
      ["154", "Ruby Roulette", "Grog", "","0","n/a"],
      ["155", "Amethyst Drop", "Grog", "","0","n/a"],
      ["156", "Diamond Daze", "Grog", "","0","n/a"],
      ["157", "Burning Ember", "Grog", "","0","n/a"],
      ["158", "Sextant Sake", "Grog", "","0","n/a"],
      ["159", "Tears of the Goddess", "Grog", "","0","n/a"],
      ["160", "Wrath of the Gods", "Grog", "","0","n/a"],
      ["161", "Titan Bound", "Grog", "","0","n/a"],
      ["162", "Globe Trotter", "Grog", "","0","n/a"],
      ["163", "Thames Arms", "Grog", "","0","n/a"],
      ["164", "Malibu Hlaahu", "Grog", "","0","n/a"],
      ["165", "Amazon Grub", "Grog", "","0","n/a"],
      ["166", "Cape de Malaga", "Grog", "","0","n/a"],
      ["167", "Viking War Brew", "Grog", "","0","n/a"],
      ["168", "Imperial March", "Grog", "","0","n/a"],
      ["169", "Blackbeard's Fortune", "Grog", "","0","n/a"],
      ["170", "Calamity Witch", "Grog", "","0","n/a"],
      ["171", "Prize of Persia", "Grog", "","0","n/a"],
      ["172", "Dreadnought", "Grog", "","0","n/a"],
      ["173", "Stairway to Heaven", "Grog", "","0","n/a"],
      ["174", "Hide n Seek Potion", "Grog", "","0","n/a"],
      ["175", "Tarantula Tingle", "Grog", "","0","n/a"],
      ["176", "Hint of Rebirth", "Grog", "","0","n/a"],
      ["177", "End of the Line", "Grog", "","0","n/a"],
      ["178", "Diamond Vapour", "Grog", "","0","n/a"],
      ["179", "Vasco de Gama", "Grog", "","0","n/a"],
      ["180", "Santa Maria", "Grog", "","0","n/a"],
      ["181", "Barnacle Bill", "Grog", "","0","n/a"],
      ["182", "Drydock Dredge", "Grog", "","0","n/a"],
      ["183", "Mayflower Punch", "Grog", "","0","n/a"],
      ["184", "Kaiser Schnapps", "Grog", "","0","n/a"],
      ["185", "Kaiserin Gin", "Grog", "","0","n/a"],
      ["186", "Red Palace", "Grog", "","0","n/a"],
      ["187", "Parley", "Grog", "","0","n/a"],
      ["188", "Rolling Thunder", "Grog", "","0","n/a"],
      ["189", "Rum Runners Poison", "Grog", "","0","n/a"],
      ["190", "Cooks Carriage", "Grog", "","0","n/a"],
      ["191", "Harpy Tears", "Grog", "","0","n/a"],
      ["192", "Pineapple Depth Charge", "Grog", "","0","n/a"],
      ["193", "Tornado", "Grog", "","0","n/a"],
      ["194", "Hangmans Ballet", "Grog", "","0","n/a"],
      ["195", "Petal Port", "Grog", "","0","n/a"],
      ["196", "Mermaid Tears", "Grog", "","0","n/a"],
      ["197", "Cap'n Kraken", "Grog", "","0","n/a"],
      ["198", "Black Jack 21", "Grog", "","0","n/a"],
      ["199", "Jamestown Mortimer", "Grog", "","0","n/a"],
      ["200", "Barbarossa", "Grog", "","0","n/a"],
      ["201", "Bottle 'o Milk", "Potion", "Boil some milk for some time...", "1","GodsDead - 18/1/2021"]
];

jQuery(document).ready(function($) {

      $('#BrewingTable').DataTable( {
            pageLength: 50,
            responsive: true,
            data: BrewingDataSet,
            columns: [
                  { title: "ID" },
                  { title: "Name" },
                  { title: "Type" },
                  { title: "How to brew" },
                  { title: "New" },
                  { title: "Discovered" },
          ],
          "columnDefs": [
            {
                "targets": [ 4 ],
                "visible": false,
                "searchable": false
            }
            ],
          "createdRow": function( row, data, dataIndex){
                  if( data[4] ==  `1`){
                        $(row).addClass('table-success');
                  }
                  else if(data[4] ==  `2`)
                  {
                        $(row).addClass('table-warning');   
                  }
             },
             "scrollX": true,

             "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",

      } );




} );