var DhowDataSet = [
    ["Oak Wood Plank", "planks","no","25%","15"],
    ["Flowing Lava", "flowing_lava","no","no","0"],
    ["Still Lava", "lava","no","no","0"],
    ["Oak Wood", "log","no","25%","10"],
    ["Glass", "glass","no","no","1.5"],
    ["Note Block", "noteblock","no","no","4"],
    ["Bed", "bed","no","no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Double Wooden Slab", "double_wooden_slab","no","25%","15"],
    ["Wooden Slab", "stone_slab","no","no","15"],
    ["TNT", "tnt","no","no","0"],
    ["Bookshelf", "bookshelf","no","no","7.5"],
    ["Torch", "torch","no","no","0"],
    ["Oak Wood Stairs", "oak_stairs","no","25%","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire","no","no","0"],
    ["Crafting Table", "crafting_table","no","no","12.5"],
    ["Furnace", "furnace","no","no","17.5"],
    ["Burning Furnace", "lit_furnace","no","no","17.5"],
    ["Standing Sign Block", "standing_sign","no","no","5"],
    ["Wooden Door Block", "wooden_door","no","no","15"],
    ["Ladder", "ladder","no","no","2"],
    ["Wall-mounted Sign Block", "wall_sign","no","no","5"],
    ["Lever", "lever","no","no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate","no","no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate","no","no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch","no","no","0"],
    ["Redstone Torch", "on redstone_torch","no","no","0"],
    ["Stone Button", "stone_button","no","no","2.5"],
    ["Oak Fence", "fence","no","no","15"],
    ["Glowstone", "glowstone","no","no","1.5"],
    ["Cake Block", "cake","no","no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater","no","no","0"],
    ["Redstone Repeater Block", "on powered_repeater","no","no","0"],
    ["White Stained Glass", "stained_glass","no","no","1.5"],
    ["Wooden Trapdoor", "trapdoor","no","no","15"],
    ["Iron Bars", "iron_bars","no","no","30"],
    ["Glass Pane", "glass_pane","no","no","1.5"],
    ["Oak Fence Gate", "fence_gate","no","no","15"],
    ["Nether Brick Fence", "nether_brick_fence","no","no","30"],
    ["Redstone Lamp", "inactive redstone_lamp","no","no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp","no","no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab","no","25%","15"],
    ["Oak Wood Slab", "wooden_slab","no","25%","15"],
    ["Ender Chest", "ender_chest","no","no","3000"],
    ["Tripwire Hook", "tripwire_hook","no","no","0"],
    ["Spruce Wood Stairs", "spruce_stairs","no","25%","15"],
    ["Birch Wood Stairs", "birch_stairs","no","25%","15"],
    ["Jungle Wood Stairs", "jungle_stairs","no","25%","15"],
    ["Flower Pot", "flower_pot","no","no","0"],
    ["Wooden Button", "wooden_button","no","no","2.5"],
    ["Mob Head", "skull","no","no","5"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate","no","no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate","no","no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator","no","no","0"],
    ["Redstone Comparator", "active powered_comparator","no","no","0"],
    ["Daylight Sensor", "daylight_detector","no","no","1"],
    ["Redstone Block", "redstone_block","no","no","30"],
    ["Dropper", "dropper","no","no","17.5"],
    ["White Stained Clay", "stained_hardened_clay","no","no","21"],
    ["White Stained Glass Pane", "stained_glass_pane","no","no","1.5"],
    ["Acacia Wood", "logs2","no","25%","10"],
    ["Acacia Wood Stairs", "acacia_stairs","no","25%","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs","no","25%","15"],
    ["Sea Lantern", "sea_lantern","no","no","1.5"],
    ["White Carpet", "carpet","no","no","0.5"],
    ["Hardened Clay", "hardened_clay","no","no","21"],
    ["Block of Coal", "coal_block","no","no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate","no","no","15"],
    ["Birch Fence Gate", "birch_fence_gate","no","no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate","no","no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate","no","no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate","no","no","15"],
    ["Spruce Fence", "spruce_fence","no","no","15"],
    ["Birch Fence", "birch_fence","no","no","15"],
    ["Jungle Fence", "jungle_fence","no","no","15"],
    ["Dark Oak Fence", "dark_oak_fence","no","no","15"],
    ["Acacia Fence", "acacia_fence","no","no","15"],
    ["Spruce Door Block", "spruce_door","no","no","15"],
    ["Birch Door Block", "birch_door","no","no","15"],
    ["Jungle Door Block", "jungle_door","no","no","15"],
    ["Dark Oak Door Block", "dark_oak_door","no","no","15"],
    ["Acacia Door Block", "acacia_door","no","no","15"],
    ["Item Frame", "item_frame","no","no","0"]
    ];
    
    var SchoonerDataSet = [
    ["Oak Wood Plank", "planks","no","25%","15"],
    ["Oak Wood", "log","no","no","10"],
    ["Glass", "glass","no","no","1.5"],
    ["Note Block", "noteblock","no","no","4"],
    ["Bed", "bed","no","no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Double Wooden Slab", "double_wooden_slab","no","no","15"],
    ["Wooden Slab", "stone_slab","no","no","15"],
    ["TNT", "tnt","no","no","0"],
    ["Bookshelf", "bookshelf","no","no","7.5"],
    ["Torch", "torch","no","no","0"],
    ["Oak Wood Stairs", "oak_stairs","no","25%","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire","no","no","0"],
    ["Crafting Table", "crafting_table","no","no","12.5"],
    ["Furnace", "furnace","no","no","17.5"],
    ["Burning Furnace", "lit_furnace","no","no","17.5"],
    ["Standing Sign Block", "standing_sign","no","no","5"],
    ["Wooden Door Block", "wooden_door","no","no","15"],
    ["Ladder", "ladder","no","no","2"],
    ["Wall-mounted Sign Block", "wall_sign","no","no","5"],
    ["Lever", "lever","no","no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate","no","no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate","no","no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch","no","no","0"],
    ["Redstone Torch", "on redstone_torch","no","no","0"],
    ["Stone Button", "stone_button","no","no","2.5"],
    ["Oak Fence", "fence","no","no","15"],
    ["Glowstone", "glowstone","no","no","1.5"],
    ["Cake Block", "cake","no","no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater","no","no","0"],
    ["Redstone Repeater Block", "on powered_repeater","no","no","0"],
    ["White Stained Glass", "stained_glass","no","no","1.5"],
    ["Wooden Trapdoor", "trapdoor","no","no","15"],
    ["Iron Bars", "iron_bars","no","no","30"],
    ["Glass Pane", "glass_pane","no","no","1.5"],
    ["Oak Fence Gate", "fence_gate","no","no","15"],
    ["Nether Brick Fence", "nether_brick_fence","no","no","30"],
    ["Redstone Lamp", "inactive redstone_lamp","no","no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp","no","no", "1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab","no","no","15"],
    ["Oak Wood Slab", "wooden_slab","no","no","15"],
    ["Ender Chest", "ender_chest","no","no","3000"],
    ["Tripwire Hook", "tripwire_hook","no","no","0"],
    ["Spruce Wood Stairs", "spruce_stairs","no","25%","15"],
    ["Birch Wood Stairs", "birch_stairs","no","25%","15"],
    ["Jungle Wood Stairs", "jungle_stairs","no","25%","15"],
    ["Flower Pot", "flower_pot","no","no","0"],
    ["Wooden Button", "wooden_button","no","no","2.5"],
    ["Mob Head", "skull","no","no","5"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate","no","no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate","no","no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator","no","no","0"],
    ["Redstone Comparator", "active powered_comparator","no","no","0"],
    ["Daylight Sensor", "daylight_detector","no","no","1"],
    ["Redstone Block", "redstone_block","no","no","30"],
    ["Dropper", "dropper","no","no","17.5"],
    ["White Stained Clay", "stained_hardened_clay","no","no","21"],
    ["White Stained Glass Pane", "stained_glass_pane","no","no","1.5"],
    ["Acacia Wood", "logs2","no","25%","10"],
    ["Acacia Wood Stairs", "acacia_stairs","no","25%","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs","no","25%","15"],
    ["Sea Lantern", "sea_lantern","no","no","1.5"],
    ["White Carpet", "carpet","no","no","0.5"],
    ["Hardened Clay", "hardened_clay","no","no","21"],
    ["Block of Coal", "coal_block","no","no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate","no","no","15"],
    ["Birch Fence Gate", "birch_fence_gate","no","no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate","no","no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate","no","no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate","no","no","15"],
    ["Spruce Fence", "spruce_fence","no","no","15"],
    ["Birch Fence", "birch_fence","no","no","15"],
    ["Jungle Fence", "jungle_fence","no","no","15"],
    ["Dark Oak Fence", "dark_oak_fence","no","no","15"],
    ["Acacia Fence", "acacia_fence","no","no","15"],
    ["Spruce Door Block", "spruce_door","no","no","15"],
    ["Birch Door Block", "birch_door","no","no","15"],
    ["Jungle Door Block", "jungle_door","no","no","15"],
    ["Dark Oak Door Block", "dark_oak_door","no","no","15"],
    ["Acacia Door Block", "acacia_door","no","no","15"],
    ["Item Frame", "item_frame","no","no","nodamge"]
    ];
    
    var BargeDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Flowing Lava", "flowing_lava", "no", "no","0"],
    ["Still Lava", "lava", "no", "no","0"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Blocks", "iron_block", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Enchantment Table", "enchanting_table", "no", "no","6000"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Oak Wood Slab", "wooden_slab", "no", "no","15"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var BrigDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Flowing Lava", "flowing_lava", "no", "no","0"],
    ["Still Lava", "lava", "no", "no","0"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Enchantment Table", "enchanting_table", "no", "no","6000"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Oak Wood Slab", "wooden_slab", "no", "no","15"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var FrigateDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Flowing Lava", "flowing_lava", "no", "no","0"],
    ["Still Lava", "lava", "no", "no","0"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","15"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Enchantment Table", "enchanting_table", "no", "no","6000"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Oak Wood Slab", "wooden_slab", "no", "no","15"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var GalleonDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Flowing Lava", "flowing_lava", "no", "no","0"],
    ["Still Lava", "lava", "no", "no","0"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Double Stone Slab", "double_stone_slab", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no", "2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Enchantment Table", "enchanting_table", "no", "no","6000"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Oak Wood Slab", "wooden_slab", "no", "no","15"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Trapped Chest", "trapped_chest", "no", "no","12.5"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var ManowarDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Flowing Lava", "flowing_lava", "no", "no","0"],
    ["Still Lava", "lava", "no", "no","0"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Enchantment Table", "enchanting_table", "no", "no","6000"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Oak Wood Slab", "wooden_slab", "no", "no","15"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var IndiamanDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Flowing Lava", "flowing_lava", "no", "no","0"],
    ["Still Lava", "lava", "no", "no","0"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Enchantment Table", "enchanting_table", "no", "no","6000"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Oak Wood Slab", "wooden_slab", "no", "no","15"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var BarracudaDataSet = [
    ["Glass", "glass", "no", "no","1.5"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Double Stone Slab", "double_stone_slab", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["Stone Brick Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Prismarine", "Prismarine", "no", "no","30"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var SeawolfDataSet = [
    ["Glass", "glass", "no", "no","1.5"],
    ["Bed", "bed", "no", "no","1"],
    ["Wool", "wool", "no", "15%","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Double Stone Slab", "double_stone_slab", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["Stone Brick Slab", "stone_slab", "no", "no","30"],
    ["TNT", "tnt", "no", "no","0"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Furnace", "furnace", "no", "no","17.5"],
    ["Burning Furnace", "lit_furnace", "no", "no","17.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Wooden Door Block", "wooden_door", "no", "no","15"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Cake Block", "cake", "no", "no","2.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Oak Fence Gate", "fence_gate", "no", "no","15"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Brewing Stand", "brewing_stand", "no", "no","2.5"],
    ["Cauldron", "cauldron", "no", "no","10"],
    ["Dragon Egg", "dragon_egg", "no", "no","45"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Ender Chest", "ender_chest", "no", "no","3000"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Beacon", "beacon", "no", "no","15"],
    ["Flower Pot", "flower_pot", "no", "no","0"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Prismarine", "Prismarine", "no", "no","30"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["White Carpet", "carpet", "no", "no","0.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Spruce Door Block", "spruce_door", "no", "no","15"],
    ["Birch Door Block", "birch_door", "no", "no","15"],
    ["Jungle Door Block", "jungle_door", "no", "no","15"],
    ["Dark Oak Door Block", "dark_oak_door", "no", "no","15"],
    ["Acacia Door Block", "acacia_door", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var WoodTurretDataSet = [
    ["Oak Wood Plank", "planks", "no", "no","15"],
    ["Oak Wood", "log", "no", "no","10"],
    ["Glass", "glass", "no", "no","1.5"],
    ["Note Block", "noteblock", "no", "no","4"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Wooden Slab", "stone_slab", "no", "no","15"],
    ["Wooden Slab", "stone_slab", "no", "no","15"],
    ["Bookshelf", "bookshelf", "no", "no","7.5"],
    ["Torch", "torch", "no", "no","0"],
    ["Oak Wood Stairs", "oak_stairs", "no", "no","15"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Crafting Table", "crafting_table", "no", "no","12.5"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Oak Fence", "fence", "no", "no","15"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Double Oak Wood Slab", "double_wooden_slab", "no", "no","15"],
    ["Dark Oak Wood Plank", "planks", "no", "no","15"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Spruce Wood Stairs", "spruce_stairs", "no", "no","15"],
    ["Birch Wood Stairs", "birch_stairs", "no", "no","15"],
    ["Jungle Wood Stairs", "jungle_stairs", "no", "no","15"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Acacia Wood", "logs2", "no", "no","10"],
    ["Acacia Wood Stairs", "acacia_stairs", "no", "no","15"],
    ["Dark Oak Wood Stairs", "dark_oak_stairs", "no", "no","15"],
    ["Spruce Fence Gate", "spruce_fence_gate", "no", "no","15"],
    ["Birch Fence Gate", "birch_fence_gate", "no", "no","15"],
    ["Jungle Fence Gate", "jungle_fence_gate", "no", "no","15"],
    ["Dark Oak Fence Gate", "dark_oak_fence_gate", "no", "no","15"],
    ["Acacia Fence Gate", "acacia_fence_gate", "no", "no","15"],
    ["Spruce Fence", "spruce_fence", "no", "no","15"],
    ["Birch Fence", "birch_fence", "no", "no","15"],
    ["Jungle Fence", "jungle_fence", "no", "no","15"],
    ["Dark Oak Fence", "dark_oak_fence", "no", "no","15"],
    ["Acacia Fence", "acacia_fence", "no", "no","15"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];
    
    var StoneTurretDataSet = [
    ["Glass", "glass", "no", "no","1.5"],
    ["Gold Block", "gold_block", "no", "no","30"],
    ["Iron Block", "iron_block", "no", "no","30"],
    ["Double Stone Slab", "double_stone_slab", "no", "no","30"],
    ["Stone Slab", "stone_slab", "no", "no","30"],
    ["Cobblestone Slab", "stone_slab", "no", "no","30"],
    ["Brick Slab", "stone_slab", "no", "no","30"],
    ["Stone Brick Slab", "stone_slab", "no", "no","30"],
    ["Quartz Slab", "stone_slab", "no", "no","4"],
    ["Obsidian", "obsidian", "10%", "no","6000"],
    ["Torch", "torch", "no", "no","0"],
    ["Chest", "chest", "4%", "no","12.5"],
    ["Redstone Wire", "redstone_wire", "no", "no","0"],
    ["Diamond Block", "diamond_block", "no", "no","30"],
    ["Standing Sign Block", "standing_sign", "no", "no","5"],
    ["Ladder", "ladder", "no", "no","2"],
    ["Cobblestone Stairs", "stone_stairs", "no", "no","30"],
    ["Wall-mounted Sign Block", "wall_sign", "no", "no","5"],
    ["Lever", "lever", "no", "no","2.5"],
    ["Stone Pressure Plate", "stone_pressure_plate", "no", "no","2.5"],
    ["Wooden Pressure Plate", "wooden_pressure_plate", "no", "no","2.5"],
    ["Redstone Torch", "off unlit_redstone_torch", "no", "no","0"],
    ["Redstone Torch", "on redstone_torch", "no", "no","0"],
    ["Stone Button", "stone_button", "no", "no","2.5"],
    ["Clay", "clay", "no", "no","3"],
    ["Netherrack", "netherrack", "no", "no","2"],
    ["Glowstone", "glowstone", "no", "no","1.5"],
    ["Redstone Repeater Block", "off unpowered_repeater", "no", "no","0"],
    ["Redstone Repeater Block", "on powered_repeater", "no", "no","0"],
    ["White Stained Glass", "stained_glass", "no", "no","1.5"],
    ["Wooden Trapdoor", "trapdoor", "no", "no","15"],
    ["Stone Bricks", "stonebrick", "no", "no","30"],
    ["Iron Bars", "iron_bars", "no", "no","30"],
    ["Glass Pane", "glass_pane", "no", "no","1.5"],
    ["Stone Brick Stairs", "stone_brick_stairs", "no", "no","30"],
    ["Nether Brick", "nether_brick", "no", "no","30"],
    ["Nether Brick Fence", "nether_brick_fence", "no", "no","30"],
    ["Nether Brick Stairs", "nether_brick_stairs", "no", "no","30"],
    ["Redstone Lamp", "inactive redstone_lamp", "no", "no","1.5"],
    ["Redstone Lamp", "active lit_redstone_lamp", "no", "no","1.5"],
    ["Tripwire Hook", "tripwire_hook", "no", "no","0"],
    ["Emerald Block", "emerald_block", "no", "no","30"],
    ["Cobblestone Wall", "cobblestone_wall", "no", "no","15.5"],
    ["Wooden Button", "wooden_button", "no", "no","2.5"],
    ["Mob Head", "skull", "no", "no","5"],
    ["Anvil", "anvil", "no", "no","6000"],
    ["Weighted Pressure Plate", "light light_weighted_pressure_plate", "no", "no","2.5"],
    ["Weighted Pressure Plate", "heavy heavy_weighted_pressure_plate", "no", "no","2.5"],
    ["Redstone Comparator", "inactive unpowered_comparator", "no", "no","0"],
    ["Redstone Comparator", "active powered_comparator", "no", "no","0"],
    ["Daylight Sensor", "daylight_detector", "no", "no","1"],
    ["Redstone Block", "redstone_block", "no", "no","30"],
    ["Hopper", "hopper", "no", "no","24"],
    ["Quartz Block", "quartz_block", "no", "no","4"],
    ["Quartz Stairs", "quartz_stairs", "no", "no","4"],
    ["Dropper", "dropper", "no", "no","17.5"],
    ["White Stained Clay", "stained_hardened_clay", "no", "no","21"],
    ["White Stained Glass Pane", "stained_glass_pane", "no", "no","1.5"],
    ["Sea Lantern", "sea_lantern", "no", "no","1.5"],
    ["Hardened Clay", "hardened_clay", "no", "no","21"],
    ["Block of Coal", "coal_block", "no", "no","30"],
    ["Item Frame", "item_frame", "no", "no","0"]
    ];

jQuery(document).ready(function($) {

    $('#DhowBlockTable').DataTable( {
        pageLength: 25,
        data: DhowDataSet,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#SchoonerBlockTable').DataTable( {
        pageLength: 25,
        data: SchoonerDataSet,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#BargeBlockTable').DataTable( {
        pageLength: 25,
        data: BargeDataSet,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#BrigBlockTable').DataTable( {
        data: BrigDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#FrigateBlockTable').DataTable( {
        data: FrigateDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#GalleonBlockTable').DataTable( {
        data: GalleonDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#ManowarBlockTable').DataTable( {
        data: ManowarDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );
    
    $('#IndiamanBlockTable').DataTable( {
        data: IndiamanDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#BarracudaBlockTable').DataTable( {
        data: BarracudaDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#SeawolfBlockTable').DataTable( {
        data: SeawolfDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#WoodTurretBlockTable').DataTable( {
        data: WoodTurretDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    $('#StoneTurretBlockTable').DataTable( {
        data: StoneTurretDataSet,
        pageLength: 25,
        columns: [
            { title: "Block Name" },
            { title: "Source ID" },
            { title: "Limited" },
            { title: "Required" },
            { title: "Blast resistance" },
        ],


        "createdRow": function( row, data, dataIndex){
            if( data[2] !=  `no`){
                  $(row).addClass('table-warning');
            }
            else if(data[3] !=  `no`)
            {
                  $(row).addClass('table-success');   
            }
       },

        "dom": "<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'p><'col-sm-12 col-md-4'f>>" +
       "<'row'<'col-sm-12'tr>>" +
       "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    } );

    //Bootstrap lightbox
    $(document).on('click', '[data-toggle="lightbox"]', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });

} );